# Generated by Django 2.2.9 on 2020-01-31 19:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount for this payment, in USD ($)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('source', models.CharField(choices=[('online', 'Online'), ('check', 'Check'), ('cash', 'Cash')], help_text='Method by which this payment was made', max_length=255)),
                ('paid_by', models.CharField(help_text='Name of person, meeting, or organization that made this payment', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment', modelcluster.fields.ParentalKey(help_text='Choose a registrant to which this payment should be applied', on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='payments.Payment')),
            ],
        ),
    ]
