# Generated by Django 2.2.9 on 2020-01-11 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrantPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrants', to='payments.Payment')),
                ('registrant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='registration.Registrant')),
            ],
        ),
    ]
