# Generated by Django 2.2.9 on 2020-01-13 16:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_registrantpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrantpayment',
            name='amount',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
