# Generated by Django 2.2.9 on 2020-01-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_registrantpayment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payee',
            field=models.CharField(default='Anonymous', help_text='Name of person, meeting, or organization that made this payment.', max_length=255),
            preserve_default=False,
        ),
    ]
