# Generated by Django 2.2.9 on 2020-01-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20200113_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='source',
            field=models.CharField(choices=[('online', 'Online'), ('check', 'Check'), ('cash', 'Cash')], default='cash', max_length=255),
            preserve_default=False,
        ),
    ]
