# Generated by Django 2.2.9 on 2020-01-13 17:36

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_payment_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.FloatField(help_text='Amount for this payment, in USD ($)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_by',
            field=models.CharField(help_text='Name of person, meeting, or organization that made this payment', max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='source',
            field=models.CharField(choices=[('online', 'Online'), ('check', 'Check'), ('cash', 'Cash')], help_text='Method by which this payment was made', max_length=255),
        ),
        migrations.AlterField(
            model_name='registrantpayment',
            name='payment',
            field=modelcluster.fields.ParentalKey(help_text='Choose a registrant to which this payment should be applied', on_delete=django.db.models.deletion.PROTECT, related_name='registrant_payments', to='payments.Payment'),
        ),
        migrations.AlterField(
            model_name='registrantpayment',
            name='registrant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrant', to='registration.Registrant'),
        ),
    ]
