# Generated by Django 2.2.9 on 2020-01-31 14:30

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_auto_20200131_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='payment',
            field=modelcluster.fields.ParentalKey(help_text='Choose a registrant to which this payment should be applied', on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='payments.Payment'),
        ),
    ]
