# Generated by Django 2.2.9 on 2020-01-31 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_auto_20200131_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='registrant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='registration.Registrant'),
        ),
    ]
