# Generated by Django 2.2.9 on 2020-01-31 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_auto_20200131_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount for this payment, in USD ($)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
