# Generated by Django 2.2.9 on 2020-01-31 15:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_auto_20200131_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
