# Generated by Django 2.2.9 on 2020-02-01 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0003_delete_accommodationprice'),
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccommodationPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accommodation_prices', to='accommodations.Accommodation')),
            ],
            options={
                'db_table': 'accommodation_price',
            },
        ),
    ]
