# Generated by Django 2.2.9 on 2020-02-01 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0003_delete_accommodationprice'),
        ('fees', '0002_accommodationprice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccommodationPrice',
            new_name='AccommodationFee',
        ),
    ]
