# Generated by Django 2.2.9 on 2020-02-01 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_auto_20200201_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accommodationfee',
            old_name='daily_price',
            new_name='daily_fee',
        ),
        migrations.AlterModelTable(
            name='accommodationfee',
            table='accommodation_fee',
        ),
    ]
