# Generated by Django 2.2.9 on 2020-02-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0004_auto_20200201_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationfee',
            name='full_week_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
