# Generated by Django 2.2.9 on 2020-02-01 20:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0006_auto_20200201_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationfee',
            name='age_max',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='accommodationfee',
            name='age_min',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
