# Generated by Django 2.2.9 on 2020-02-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0007_auto_20200201_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationfee',
            name='daily_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
