# Generated by Django 2.2.9 on 2020-01-31 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('age_groups', '0001_initial'),
        ('accommodations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccommodationPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accommodation_prices', to='accommodations.Accommodation')),
                ('age_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accommodation_prices', to='age_groups.AgeGroup')),
            ],
        ),
    ]
