# Generated by Django 2.2.9 on 2020-02-01 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0002_auto_20200201_2015'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccommodationPrice',
        ),
    ]
