# Generated by Django 2.2.9 on 2020-01-31 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('age_groups', '0001_initial'),
        ('accommodations', '0002_accommodationprice'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accommodationprice',
            unique_together={('accommodation', 'age_group')},
        ),
        migrations.AlterModelTable(
            name='accommodationprice',
            table='accommodation_price',
        ),
    ]
