# Generated by Django 2.2.9 on 2020-01-31 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0003_auto_20200131_1538'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accommodationprice',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='accommodationprice',
            name='age_group',
        ),
    ]
