# Generated by Django 2.2.9 on 2020-01-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrant',
            name='needs_ada_accessible_accommodations',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
