# Generated by Django 2.2.9 on 2020-01-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_registrant_needs_ada_accessible_accommodations'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrant',
            name='email',
            field=models.EmailField(blank=True, help_text='Personal email for this registrant, if applicable.', max_length=254, null=True),
        ),
    ]
