# Generated by Django 2.2.9 on 2020-01-31 18:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_registrationpage_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrant',
            name='age',
            field=models.IntegerField(default=0, help_text='Age at time of the event.', validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
