# Generated by Django 2.2.9 on 2020-01-31 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Choose one of the event days', unique=True)),
                ('partial_day_discount', models.IntegerField(blank=True, help_text='Enter the optional amount in USD that each day registration should be discounted on this date.', null=True)),
            ],
            options={
                'db_table': 'event_day',
            },
        ),
    ]
